
env: "prod"  # "dev" "prod"
debug: false

host: "0.0.0.0"
port: 8085
data_dir: "docs"
max_file_size: 0
buffer_size: 65536  # 64M

# 可能用到的ai接口，暂时只写个这个
ollama_url: "http://localhost:11434"

admin_enable: true
admin_totp_secret: "HJYXOOXWRRNRQSH3GTGEWM3V6IHU75ZJ"
admin_bypass_auth: false

es_host: "https://[::1]:9200"
es_api_key: "6FEx_0jQrZu8Igr5uC3sBQ"
es_api_key_encoded: "SnIyWDhaMEJVNHdvNDVSZ3loQTI6NkZFeF8walFyWnU4SWdyNXVDM3NCUQ=="
# 如果使用证书，填写证书路径。否则连接时忽略证书错误。
es_cert: false
es_index_prefix: "vanilla-wiki"

icp_host:
  - "vanilla.wiki"
icp_number: "苏ICP备2026007004号-1"
public_security_link: "https://beian.mps.gov.cn/#/query/webSearch?code=32011302323086"
public_security_number: "苏公网安备32011302323086号"
public_security: '<a href="https://beian.mps.gov.cn/#/query/webSearch?code=32011302323086" rel="noreferrer" target="_blank" class="text-secondary" style="text-decoration:none;">苏公网安备32011302323086号</a>'
